---
title       : Melbourne House Prices Map Application
subtitle    : A Shiny based application for Finding Houses in Melbourne
author      : Paolo Coraggio
job         : 
framework   : revealjs      # {io2012, html5slides, shower, dzslides, ...}
highlighter : highlight.js  # {highlight.js, prettify, highlight}
hitheme     : tomorrow      # 
revealjs    :
  theme: night
  transition: page
widgets     : []            # {mathjax, quiz, bootstrap}
mode        : selfcontained # {standalone, draft}
knit        : slidify::knit2slides
logo        : MelbourneLogo.png
---

<style>
.reveal h1 {
    font-size: 2em;
    // color: #0000b3;
    padding-bottom: 10px;
}

.reveal h2 {
    font-size: 1.5em;
    //color: #fff7e6;
    padding-bottom: 10px;
}


.reveal p, .reveal em {
    padding-bottom: 10px;
    width: 960px;
}

.reveal p {
    font-size: .75em;
}

.reveal small {
    width: 500px;
}


.reveal .slides {
    text-align: left;
}

.reveal .roll {
    vertical-align: text-bottom;
}


code {
    color: red;
}

.reveal pre code { 
     height: 80px;
}
</style>

## Melbourne House Prices Map App

An Interactive Shiny Application to help you to find home in Melbourne, Australia

<left>
<small> author: Paolo Coraggio </small>
</left>

<small> date: 14.02.2020 </small>

--- .class #id 

## The Melbourne House Prices Application

The __MHPMap application__ is an interactive application helping you to find a house in Melbourne, Australia 

.fragment __Select__ your criteria (e.g. number of Rooms, Bathrooms, 
City district, Price Range) from the Drop Down and Slider menu

.fragment __Visualise__ whithin an interactive map where the matching houses are located 

.fragment __Compare__ the mean prices of your criteria with the rest of the city

.fragment MHPMap is a [shiny](https://shiny.rstudio.com/) based application. You can find its full code on [GitHub](https://github.com/pacoraggio/MelbourneHousePriceShinyApp) 

--- .class #id 

## Parameter Selection

- The house data are available on [Kaggle](https://www.kaggle.com/anthonypino/melbourne-housing-market#Melbourne_housing_FULL.csv) and consist of more than 30k records containing information about house location, number of rooms, price, distance from the Melbourne business center and so on.
- From the User Interface you can select the following parameters:
  - Number of Rooms
  - Number of Bathrooms
  - Type of Residency (house, unit/duplex/, town house)
  - In which Melbourne region you want to search
  - The price range
- This parameters are used to filter the data.frame created from the .csv file and the resulting data are displayed on the Melbourne Map

--- .class #id 

## Map Visualization 

This is a map visualization for `houses` type with `3` rooms, `2` bathrooms, in Melbourne `Southern Metropolitan` area  

```{r echo=TRUE, fig.align='left', message=FALSE, warning=FALSE, results='asis'}

library(plotly)
load("dfmelPres.Rdata")

m = list(
  l = 5,
  r = 5,
  b = 5,
  t = 5,
  pad = 1
)


l <- list(
  font = list(
    size = 8,
    color = "#000"),
  
  bgcolor = "#E2E2E2",
  bordercolor = "#FFFFFF",
  orientation = 'v',
  borderwidth = 10)


p <- plot_ly(df.melPres, type = "scattermapbox") %>%
    add_trace(lat = filter(df.melPres, PriceCategory == "low")$Lattitude,
              lon = filter(df.melPres, PriceCategory == "low")$Longtitude,
              color = paste("<b>Low Price</b>","<br> < 660k"),
              marker = list(color = "darkgreen"),
              hoverinfo = "text",
              hovertext = filter(df.melPres, PriceCategory == "low")$HoverText,
              mode = "markers") %>%
    add_trace(lat = filter(df.melPres, PriceCategory == "medium low")$Lattitude,
              lon = filter(df.melPres, PriceCategory == "medium low")$Longtitude,
              color = paste("<b>Medium Low Price</b>", "<br> 660k - 910k"),
              marker = list(color = "green"),
              hoverinfo = "text",
              hovertext = filter(df.melPres, PriceCategory == "medium low")$HoverText,
              mode = "markers") %>%
    add_trace(lat = filter(df.melPres, PriceCategory == "medium high")$Lattitude,
              lon = filter(df.melPres, PriceCategory == "medium high")$Longtitude,
              color = paste("<b>Medium High Price</b>","<br> 910K - 1.33M"),
              marker = list(color = "orange"),
              hovertext = filter(df.melPres, PriceCategory == "medium high")$HoverText,
              hoverinfo = "text",
              mode = "markers")%>%
    add_trace(lat = filter(df.melPres, PriceCategory == "high")$Lattitude,
              lon = filter(df.melPres, PriceCategory == "high")$Longtitude,
              color = paste("<b>High Price</b>","<br> > 1.33M"),
              marker = list(color = "red"),
              hovertext = filter(df.melPres, PriceCategory == "high")$HoverText,
              hoverinfo = "text",
              mode = "markers")%>%
    layout(
      margin = m,
        legend = l,
        mapbox = list(
            style = 'open-street-map',
            zoom =9.5,
            center = list(lon = mean(df.melPres$Longtitude), 
                          lat = mean(df.melPres$Lattitude)))
    )

htmlwidgets::saveWidget(p, file = "demoemap1.html")
cat('<pre><iframe src="demoemap1.html" width=100% height=350px allowtransparency="true"> </iframe></pre>')
```

--- .class #id

## Summarize and Compare


